/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import javax.swing.Timer;

import Tipografias.Fuentes;
import java.awt.Color;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author SIS-01
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    Fuentes tipoFuente;
    public Inicio() {
        initComponents();
        this.setLocationRelativeTo(null);
        tipoFuente = new Fuentes();
        txtUsuario.setFont(tipoFuente.fuente(tipoFuente.RIO,0,18));
        txtUsuario.setForeground(Color.GRAY);
        txtPassword.setFont(tipoFuente.fuente(tipoFuente.RIO, 0, 18));
        txtPassword.setForeground(Color.GRAY);
        txtPassword.setEchoChar('\0');
        txtMensaje.setFont(tipoFuente.fuente(tipoFuente.BPR,0,18));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        banner1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        TbtnVisual = new javax.swing.JToggleButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        txtMensaje = new javax.swing.JLabel();
        banner = new javax.swing.JLabel();

        banner1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Starter Login.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbtnVisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button visual_001.png"))); // NOI18N
        TbtnVisual.setToolTipText("");
        TbtnVisual.setBorder(null);
        TbtnVisual.setBorderPainted(false);
        TbtnVisual.setContentAreaFilled(false);
        TbtnVisual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbtnVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbtnVisualActionPerformed(evt);
            }
        });
        jPanel1.add(TbtnVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(250, 249, 248));
        txtUsuario.setText("Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseExited(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 360, 40));

        txtPassword.setBackground(new java.awt.Color(250, 249, 248));
        txtPassword.setText("Contraseña");
        txtPassword.setToolTipText("");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPasswordMouseExited(evt);
            }
        });
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 360, 40));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button Login_001.png"))); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button Register_001.png"))); // NOI18N
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, 60));

        txtMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(255, 0, 0));
        txtMensaje.setText(" ");
        jPanel1.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 410, 30));

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Starter Login.png"))); // NOI18N
        jPanel1.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    //BOTÓN DE REGISTRO
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        this.setVisible(false);
        Registro registro = new Registro();
        registro.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        if (txtUsuario.getText().equals("Usuario")){
            txtUsuario.setText("");
            txtUsuario.setFont(tipoFuente.fuente(tipoFuente.BPR,0,18));
            txtUsuario.setForeground(Color.BLACK);
        }
        if (new String(txtPassword.getPassword()).equals("")){
            txtPassword.setEchoChar('\0');
            txtPassword.setText("Contraseña");
            txtPassword.setFont(tipoFuente.fuente(tipoFuente.RIO,0,18));
            txtPassword.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtUsuarioMouseClicked
    //Este otro método podría ir, funciona cuando sale el mouse de la caja que contiene el textfield
    //Mejor es si clickea en el otro txt y si no hay nada la cambia, ya que si sale de la caja y se cambia se siente extraño
    private void txtUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseExited
        
    }//GEN-LAST:event_txtUsuarioMouseExited

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        if (new String(txtPassword.getPassword()).equals("Contraseña")){
            txtPassword.setText("");
            if(TbtnVisual.isSelected()){
                txtPassword.setEchoChar('\0');
                txtPassword.setFont(tipoFuente.fuente(tipoFuente.BPR,0,18));
                txtPassword.setForeground(Color.BLACK);
            }
            else{
                txtPassword.setEchoChar('\u2022');
                txtPassword.setFont(tipoFuente.fuente(tipoFuente.BPR,0,18));
                txtPassword.setForeground(Color.BLACK);
            }
        }
        if (txtUsuario.getText().equals("")){
            txtUsuario.setText("Usuario");
            txtUsuario.setFont(tipoFuente.fuente(tipoFuente.RIO,0,18));
            txtUsuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseExited
        
    }//GEN-LAST:event_txtPasswordMouseExited

    
    //BOTÓN DE LOGIN
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String u = txtUsuario.getText();
        String c = new String(txtPassword.getPassword());
        
        Timer timer = new Timer(2000, (e) -> {txtMensaje.setText("");});
        
        timer.setRepeats(false);        
        if (u.equals("Usuario") && c.equals("Contraseña")){
            txtMensaje.setText("Hacen falta campos por llenar!!!");
            timer.start();
        }
        else{
            if (u.equals("Usuario")){
                txtMensaje.setText("No se ha digitado ningún usuario!!!");
                timer.start();
            }
            else{
                if (c.equals("Contraseña")){
                    txtMensaje.setText("No se ha escrito una contraseña!!!");
                    timer.start();
                }
                else{
                    this.setVisible(false);
                    Sesion sesion = new Sesion();
                    sesion.setVisible(true);
                }
            }
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed
    
    
    private void TbtnVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbtnVisualActionPerformed
        // TODO add your handling code here:
        
        Icon blindEye,eye;
        
        blindEye = new ImageIcon(getClass().getResource("/Images/Button visual_001.png"));
        eye = new ImageIcon(getClass().getResource("/Images/Button visual_002.png"));
        
        if(TbtnVisual.isSelected()){
            TbtnVisual.setIcon(eye);
            txtPassword.setEchoChar('\0');
        }
        else{
            TbtnVisual.setIcon(blindEye);
            if(new String(txtPassword.getPassword()).equals("Contraseña")){
                
            }
            else{
                txtPassword.setEchoChar('\u2022');
            }
        }
    }//GEN-LAST:event_TbtnVisualActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton TbtnVisual;
    private javax.swing.JLabel banner;
    private javax.swing.JLabel banner1;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRegister;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
