/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

import AgenciaDeViajes.Agencia;
import static AgenciaDeViajes.Agencia.guardarEnArchivos;
import static AgenciaDeViajes.Agencia.listaUsuarios;
import static AgenciaDeViajes.Agencia.listaVuelos;
import AgenciaDeViajes.Usuario;
import javax.swing.Timer;

import Tipografias.Fuentes;
import java.awt.Color;
import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import javax.swing.JToggleButton;

/**
 *
 * @author SIS-01
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    
    public static int posicionUsuario;
    
    public Inicio() {
        initComponents();
        putImageinButton("/images/Close_Button_01.png", btnExit);
        this.setLocationRelativeTo(null);
        cursiveFontinTF(txtUsuario);
        txtUsuario.setForeground(Color.GRAY);
        txtPassword.setEchoChar('\0');
        cursiveFontinPF(txtPassword);
        txtPassword.setForeground(Color.GRAY);
        normalFontinJL(txtMensaje);
        putImageinButton("/Images/miniLogo.png",btnMini);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        absolutoPanel = new javax.swing.JPanel();
        TbtnVisual = new javax.swing.JToggleButton();
        txtUsuario = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRegister = new javax.swing.JButton();
        txtMensaje = new javax.swing.JLabel();
        Barra = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        btnMini = new javax.swing.JButton();
        banner = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        absolutoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TbtnVisual.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Button visual_001.png"))); // NOI18N
        TbtnVisual.setToolTipText("");
        TbtnVisual.setBorder(null);
        TbtnVisual.setBorderPainted(false);
        TbtnVisual.setContentAreaFilled(false);
        TbtnVisual.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TbtnVisual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TbtnVisualActionPerformed(evt);
            }
        });
        absolutoPanel.add(TbtnVisual, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 240, -1, -1));

        txtUsuario.setBackground(new java.awt.Color(250, 249, 248));
        txtUsuario.setText("Usuario");
        txtUsuario.setBorder(null);
        txtUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtUsuarioMouseExited(evt);
            }
        });
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });
        absolutoPanel.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 160, 410, 40));

        txtPassword.setBackground(new java.awt.Color(250, 249, 248));
        txtPassword.setText("Contraseña");
        txtPassword.setToolTipText("");
        txtPassword.setBorder(null);
        txtPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtPasswordMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtPasswordMouseExited(evt);
            }
        });
        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        absolutoPanel.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 360, 40));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnLogin_001.png"))); // NOI18N
        btnLogin.setBorder(null);
        btnLogin.setBorderPainted(false);
        btnLogin.setContentAreaFilled(false);
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        absolutoPanel.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, -1, -1));

        btnRegister.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/btnRegister_001.png"))); // NOI18N
        btnRegister.setBorder(null);
        btnRegister.setBorderPainted(false);
        btnRegister.setContentAreaFilled(false);
        btnRegister.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        absolutoPanel.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 410, -1, 60));

        txtMensaje.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        txtMensaje.setForeground(new java.awt.Color(255, 0, 0));
        txtMensaje.setText(" ");
        absolutoPanel.add(txtMensaje, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 410, 30));

        Barra.setOpaque(false);
        Barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                BarraMouseDragged(evt);
            }
        });
        Barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                BarraMousePressed(evt);
            }
        });
        Barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setToolTipText("");
        btnExit.setBorder(null);
        btnExit.setBorderPainted(false);
        btnExit.setContentAreaFilled(false);
        btnExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnExitMouseExited(evt);
            }
        });
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        Barra.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 10, 40, 40));

        btnMini.setBorder(null);
        btnMini.setBorderPainted(false);
        btnMini.setContentAreaFilled(false);
        btnMini.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMini.setPreferredSize(new java.awt.Dimension(40, 40));
        btnMini.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMiniActionPerformed(evt);
            }
        });
        Barra.add(btnMini, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 10, 40, 40));

        absolutoPanel.add(Barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Login.png"))); // NOI18N
        absolutoPanel.add(banner, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(absolutoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 980, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(absolutoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 612, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void putImageinButton(String ruta, JButton btn){
        ImageIcon image = new ImageIcon(getClass().getResource(ruta));
        Icon imageIcon = new ImageIcon(image.getImage().getScaledInstance(btn.getWidth(), btn.getHeight(), Image.SCALE_SMOOTH));
        btn.setIcon(imageIcon);
    }
    
    private void putImageinTButton(String ruta, JToggleButton Tbtn){
        ImageIcon image = new ImageIcon(getClass().getResource(ruta));
        Icon imageIcon = new ImageIcon(image.getImage().getScaledInstance(Tbtn.getWidth(), Tbtn.getHeight(), Image.SCALE_SMOOTH));
        Tbtn.setIcon(imageIcon);
    }
    
    Fuentes tipoFuente = new Fuentes();
    
    private void cursiveFontinTF(JTextField jtext){
        jtext.setFont(tipoFuente.fuente(tipoFuente.RIO,0,18));
    }
    
    private void cursiveFontinPF(JPasswordField jpass){
        jpass.setFont(tipoFuente.fuente(tipoFuente.RIO,0,18));
    }
    
    private void normalFontinTF(JTextField jtext){
        jtext.setFont(tipoFuente.fuente(tipoFuente.BPR,0,18));
    }
    
    private void normalFontinPF(JPasswordField jpass){
        jpass.setFont(tipoFuente.fuente(tipoFuente.BPR,0,18));
    }
    
    private void normalFontinJL(JLabel jLabel){
        jLabel.setFont(tipoFuente.fuente(tipoFuente.BPR,0,18));
    }
            
    //BOTÓN DE REGISTRO
    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        dispose();
        Registro registro = new Registro();
        registro.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void txtUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseClicked
        String ps =new String(txtPassword.getPassword());
        if (txtUsuario.getText().equals("Usuario")){
            txtUsuario.setText("");
            normalFontinTF(txtUsuario);
            txtUsuario.setForeground(Color.BLACK);
        }
        if (ps.equals("")){
            txtPassword.setText("Contraseña");
            txtPassword.setEchoChar('\0');
            cursiveFontinPF(txtPassword);
            txtPassword.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtUsuarioMouseClicked
    //Este otro método podría ir, funciona cuando sale el mouse de la caja que contiene el textfield
    //Mejor es si clickea en el otro txt y si no hay nada la cambia, ya que si sale de la caja y se cambia se siente extraño
    private void txtUsuarioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtUsuarioMouseExited
        
    }//GEN-LAST:event_txtUsuarioMouseExited

    private void txtPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseClicked
        String ps =new String(txtPassword.getPassword());
        if (ps.equals("Contraseña")){
            txtPassword.setText("");
            if(TbtnVisual.isSelected()){
                txtPassword.setEchoChar('\0');
            }
            else{
                txtPassword.setEchoChar('\u2022');
            }
            normalFontinPF(txtPassword);
            txtPassword.setForeground(Color.BLACK);
        }
        if (txtUsuario.getText().equals("")){
            txtUsuario.setText("Usuario");
            cursiveFontinTF(txtUsuario);
            txtUsuario.setForeground(Color.GRAY);
        }
    }//GEN-LAST:event_txtPasswordMouseClicked

    private void txtPasswordMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtPasswordMouseExited
        
    }//GEN-LAST:event_txtPasswordMouseExited

    
    //BOTÓN DE LOGIN
    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        String u = txtUsuario.getText();
        String c = new String(txtPassword.getPassword());
        
        Timer timer = new Timer(2000, (e) -> {txtMensaje.setText("");});
        
        timer.setRepeats(false);        
        if (u.equals("Usuario") && c.equals("Contraseña")){
            txtMensaje.setText("Hacen falta campos por llenar!!!");
            timer.start();
        }
        else{
            if (u.equals("Usuario")){
                txtMensaje.setText("No se ha digitado ningún usuario!!!");
                timer.start();
            }
            else{
                if (c.equals("Contraseña")){
                    txtMensaje.setText("No se ha escrito una contraseña!!!");
                    timer.start();
                }
                else{
                    for (int i=0 ;i < AgenciaDeViajes.Agencia.listaUsuarios.size(); i++){
                        if (AgenciaDeViajes.Agencia.listaUsuarios.get(i).login(u, c)==true){
                            if (AgenciaDeViajes.Agencia.listaUsuarios.get(i).getUserName().equals("ADMIN")){
                                dispose();
                                Admin admin = new Admin();
                                admin.setVisible(true);
                                break;
                            }
                            else{
                                posicionUsuario=i;
                                dispose();
                                Sesion sesion = new Sesion(0);
                                sesion.setVisible(true);
                                break;
                            }
                        }
                    }
                    txtMensaje.setText("Usuario/Contraseña incorrectas");
                    timer.start();
                }
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed
    
    
    private void TbtnVisualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TbtnVisualActionPerformed
        // TODO add your handling code here:
        
        if(TbtnVisual.isSelected()){
            putImageinTButton("/Images/Button visual_002.png", TbtnVisual);
            txtPassword.setEchoChar('\0');
        }
        else{
            putImageinTButton("/Images/Button visual_001.png", TbtnVisual);
            if(new String(txtPassword.getPassword()).equals("Contraseña")){
                
            }
            else{
                txtPassword.setEchoChar('\u2022');
            }
        }
    }//GEN-LAST:event_TbtnVisualActionPerformed
    
    int xMouse,yMouse;
    private void BarraMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_BarraMousePressed
    
    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void BarraMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BarraMouseDragged
        // TODO add your handling code here:
        int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        setLocation(x-xMouse, y-yMouse);
    }//GEN-LAST:event_BarraMouseDragged

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        String archivoVuelos = "Vuelos.dat", archivoUsuarios = "Usuarios.dat";
        guardarEnArchivos(listaUsuarios, archivoUsuarios);
        guardarEnArchivos(listaVuelos, archivoVuelos);
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseEntered
        // TODO add your handling code here:
        putImageinButton("/images/Close_Button_02.png", btnExit);
    }//GEN-LAST:event_btnExitMouseEntered

    private void btnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnExitMouseExited
        // TODO add your handling code here:
        putImageinButton("/images/Close_Button_01.png", btnExit);
    }//GEN-LAST:event_btnExitMouseExited

    private void btnMiniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMiniActionPerformed
        // TODO add your handling code here:
        this.setExtendedState(ICONIFIED);
    }//GEN-LAST:event_btnMiniActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Barra;
    private javax.swing.JToggleButton TbtnVisual;
    private javax.swing.JPanel absolutoPanel;
    private javax.swing.JLabel banner;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnMini;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel txtMensaje;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsuario;
    // End of variables declaration//GEN-END:variables
}
